apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T15:03:00Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3631"
  uid: 9b0bcde0-229b-4893-bec4-3e6c7d230a9a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.155.143
  clusterIPs:
  - 10.98.155.143
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30634
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
